import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/styles/globals.css";
import twclsx from "@/utils/twclsx";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Quizify",
	description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body
			className={twclsx(
				"min-h-screen flex flex-col bg-custom-black text-custom-white",
				inter.className
			)}
		>
			<Header />
			<main className="mt-40 flex-1 container">{children}</main>
			<Footer />
		</body>
	</html>
);

export default RootLayout;
