import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Providers from "@/components/Providers";
import "@/styles/globals.css";
import { getCategories } from "@/utils/fetchers";
import twclsx from "@/utils/twclsx";
import { Inter } from "next/font/google";
import useCategoriesStore from "@/stores/categoriesStore";
import CategoriesStoreInitializer from "@/components/CategoriesStoreInitializer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Quizify",
	description: "Generated by create next app"
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
	const categories = await getCategories();

	useCategoriesStore.setState({ categories });

	return (
		<html lang="en">
			<body
				className={twclsx(
					"min-h-screen flex flex-col bg-custom-black text-custom-white",
					inter.className
				)}
			>
				<Providers>
					<CategoriesStoreInitializer categories={categories} />
					<Header />
					<main className="mt-28 sm:mt-40 flex-1 container">{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
